In [6]:
import torch
import numpy as np

## **Tensor class**

In [7]:
t = torch.Tensor()
type(t)

torch.Tensor

In [8]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [9]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [10]:
t1=torch.tensor([1,2,3])
t2=torch.tensor([1.,2.,3.])

In [11]:
t1.dtype

torch.int64

In [12]:
t2.dtype

torch.float32

In [13]:
# t1+t2 # not possible

In [15]:
t1 = torch.tensor([1,2,3])
t2 = t1.cuda()

In [ ]:
t1.device

In [ ]:
t2.device

In [ ]:
# t1 + t2 # not possible

## **Creation options using data**

In [16]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [18]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [19]:
torch.tensor(data)

tensor([1, 2, 3])

In [20]:
torch.as_tensor(data)

tensor([1, 2, 3])

In [22]:
torch.from_numpy(data)

tensor([1, 2, 3])

## **Creation option without data**

In [23]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [24]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [25]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [26]:
torch.rand(2,2)

tensor([[0.2807, 0.5073],
        [0.0233, 0.5279]])