In [1]:
import torch
import numpy as np

## **Tensor class**

In [2]:
t = torch.Tensor()
type(t)

torch.Tensor

In [3]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [4]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [5]:
t1=torch.tensor([1,2,3])
t2=torch.tensor([1.,2.,3.])

In [6]:
t1.dtype

torch.int64

In [7]:
t2.dtype

torch.float32

In [8]:
# t1+t2 # not possible

In [10]:
t1 = torch.tensor([1,2,3])
# t2 = t1.cuda()

In [11]:
t1.device

device(type='cpu')

In [12]:
t2.device

device(type='cpu')

In [13]:
# t1 + t2 # not possible

## **Creation options using data**

In [14]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [15]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [16]:
torch.tensor(data)

tensor([1, 2, 3])

In [17]:
torch.as_tensor(data)

tensor([1, 2, 3])

In [ ]:
torch.from_numpy(data)

## **Creation option without data**

In [18]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [19]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [20]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [21]:
torch.rand(2,2)

tensor([[0.5912, 0.3406],
        [0.3461, 0.6678]])

## **Creating PyTorch Tensor - Best Option**

In [22]:
data = np.array([1,2,3])

In [23]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [24]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [25]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int64
torch.int64
torch.int64


In [26]:
torch.get_default_dtype()

torch.float32

In [27]:
torch.tensor(data, dtype=torch.float32)

tensor([1., 2., 3.])

In [28]:
torch.as_tensor(data, dtype=torch.float32)

tensor([1., 2., 3.])

## **Sharing Memory For Performance: Copy Vs Share**

In [29]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [30]:
data[0]=0
data[1]=0
data[2]=0

In [31]:
print(t1)
print(t2)
# copying - less efficient

tensor([1., 2., 3.])
tensor([1, 2, 3])


In [32]:
print(t3)
print(t4)
# sharing - more efficient

tensor([0, 0, 0])
tensor([0, 0, 0])


1. torch.tensor()
2. torch.as_tensor()

1. Since numpy.ndarray objects are allocated on the CPU, the as_tensor() function must copy the data from the CPU to the GPU when a GPU is being used.
2. The memory sharing of as_tensor() doesn't work with built-in Python data structures like lists.
3. The as_tensor() call requires developer knowledge of the sharing feature. This is necessary so we don't inadvertently make an unwanted change in the underlying data without realizing the change impacts multiple objects.
4. The as_tensor() performance improvement will be greater if there are a lot of back and forth operations between numpy.ndarray objects and tensor objects. However, if there is just a single load operation, there shouldn't be much impact from a performance perspective.

## **Tensor Operation Types**

1. Reshaping operations
2. Element-wise operations
3. Reduction operations
4. Access operations

## **Tensor Shape Review**

In [33]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [34]:
t.size()

torch.Size([3, 4])

In [35]:
len(t.shape)

2

In [36]:
torch.tensor(t.shape).prod()

tensor(12)

In [37]:
t.numel()

12

## **Reshaping A Tensor In PyTorch**

In [38]:
t.reshape([1,12])

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [39]:
t.reshape([2,6])

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [40]:
t.reshape([3,4])

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [41]:
t.reshape([4,3])

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [42]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [43]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [44]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

## **Changing Shape By Squeezing And Unsqueezing**

In [45]:
print(t.reshape([1,12]))
print(t.reshape([1,12]).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [57]:
# Squeezing a tensor removes the dimensions or axes that have a length of one.
print(t.reshape([1,12]).squeeze())
print(t.reshape([1,12]).squeeze().shape)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
torch.Size([12])


In [58]:
# Unsqueezing a tensor adds a dimension with a length of one.
print(t.reshape([1,12]).squeeze().unsqueeze(dim=0))
print(t.reshape([1,12]).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
torch.Size([1, 12])


## **Flatten A Tensor**

Flattening a tensor means to remove all of the dimensions except for one.

In [59]:
# def flatten(t):
#     t = t.reshape(1, -1)
#     t = t.squeeze()
#     return t
# or
def flatten(t):
    t = t.reshape(-1)
    return t

In [50]:
t = torch.ones(4, 3)
t

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [60]:
flatten(t)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## **Concatenating Tensors**

In [52]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])
t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [53]:
torch.cat((t1, t2), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [54]:
torch.cat((t1, t2), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [55]:
torch.cat((t1, t2), dim=0).shape

torch.Size([4, 2])

In [56]:
torch.cat((t1, t2), dim=1).shape

torch.Size([2, 4])