In [1]:
import torch
import numpy as np

## **Tensor class**

In [2]:
t = torch.Tensor()
type(t)

torch.Tensor

In [3]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [4]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [5]:
t1=torch.tensor([1,2,3])
t2=torch.tensor([1.,2.,3.])

In [6]:
t1.dtype

torch.int64

In [7]:
t2.dtype

torch.float32

In [8]:
# t1+t2 # not possible

In [9]:
t1 = torch.tensor([1,2,3])
# t2 = t1.cuda()

In [10]:
t1.device

device(type='cpu')

In [11]:
t2.device

device(type='cpu')

In [12]:
# t1 + t2 # not possible

## **Creation options using data**

In [13]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [14]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [15]:
torch.tensor(data)

tensor([1, 2, 3])

In [16]:
torch.as_tensor(data)

tensor([1, 2, 3])

In [17]:
torch.from_numpy(data)

tensor([1, 2, 3])

## **Creation option without data**

In [18]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [19]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [20]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [21]:
torch.rand(2,2)

tensor([[0.0834, 0.5297],
        [0.3580, 0.8735]])

## **Creating PyTorch Tensor - Best Option**

In [22]:
data = np.array([1,2,3])

In [23]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [24]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [25]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int64
torch.int64
torch.int64


In [26]:
torch.get_default_dtype()

torch.float32

In [27]:
torch.tensor(data, dtype=torch.float32)

tensor([1., 2., 3.])

In [28]:
torch.as_tensor(data, dtype=torch.float32)

tensor([1., 2., 3.])

## **Sharing Memory For Performance: Copy Vs Share**

In [29]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [30]:
data[0]=0
data[1]=0
data[2]=0

In [31]:
print(t1)
print(t2)
# copying - less efficient

tensor([1., 2., 3.])
tensor([1, 2, 3])


In [32]:
print(t3)
print(t4)
# sharing - more efficient

tensor([0, 0, 0])
tensor([0, 0, 0])


1. torch.tensor()
2. torch.as_tensor()

1. Since numpy.ndarray objects are allocated on the CPU, the as_tensor() function must copy the data from the CPU to the GPU when a GPU is being used.
2. The memory sharing of as_tensor() doesn't work with built-in Python data structures like lists.
3. The as_tensor() call requires developer knowledge of the sharing feature. This is necessary so we don't inadvertently make an unwanted change in the underlying data without realizing the change impacts multiple objects.
4. The as_tensor() performance improvement will be greater if there are a lot of back and forth operations between numpy.ndarray objects and tensor objects. However, if there is just a single load operation, there shouldn't be much impact from a performance perspective.

## **Tensor Operation Types**

1. Reshaping operations
2. Element-wise operations
3. Reduction operations
4. Access operations

## **Tensor Shape Review**

In [33]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [34]:
t.size()

torch.Size([3, 4])

In [35]:
len(t.shape)

2

In [36]:
torch.tensor(t.shape).prod()

tensor(12)

In [37]:
t.numel()

12

## **Reshaping A Tensor In PyTorch**

In [38]:
t.reshape([1,12])

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [39]:
t.reshape([2,6])

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [40]:
t.reshape([3,4])

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [41]:
t.reshape([4,3])

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [42]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [43]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [44]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

## **Changing Shape By Squeezing And Unsqueezing**

In [45]:
print(t.reshape([1,12]))
print(t.reshape([1,12]).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [46]:
# Squeezing a tensor removes the dimensions or axes that have a length of one.
print(t.reshape([1,12]).squeeze())
print(t.reshape([1,12]).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [47]:
# Unsqueezing a tensor adds a dimension with a length of one.
print(t.reshape([1,12]).squeeze().unsqueeze(dim=0))
print(t.reshape([1,12]).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


## **Flatten A Tensor**

Flattening a tensor means to remove all of the dimensions except for one.

In [48]:
# def flatten(t):
#     t = t.reshape(1, -1)
#     t = t.squeeze()
#     return t
# or
def flatten(t):
    t = t.reshape(-1)
    return t

In [49]:
t = torch.ones(4, 3)
t

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [50]:
flatten(t)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## **Concatenating Tensors**

In [51]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])
t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [52]:
torch.cat((t1, t2), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [53]:
torch.cat((t1, t2), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [54]:
torch.cat((t1, t2), dim=0).shape

torch.Size([4, 2])

In [55]:
torch.cat((t1, t2), dim=1).shape

torch.Size([2, 4])

## **Building A Tensor Representation For A Batch Of Images**

In [56]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

In [57]:
t = torch.stack((t1, t2, t3))
t.shape

torch.Size([3, 4, 4])

In [58]:
t

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

In [59]:
t = t.reshape(3,1,4,4)
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [60]:
t[0]

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [61]:
t[0][0]

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [62]:
t[0][0][0]

tensor([1, 1, 1, 1])

In [63]:
t[0][0][0][0]

tensor(1)

## **Flattening The Tensor Batch**

In [64]:
t.reshape(1,-1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [65]:
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [66]:
t.view(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [67]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

## **Flattening Specific Axes Of A Tensor**

In [68]:
t.flatten(start_dim=1).shape

torch.Size([3, 16])

In [69]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [70]:
t.reshape(3,-1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

## **Flattening An RGB Image**

In [71]:
r = torch.ones(1,2,2)
g = torch.ones(1,2,2) + 1
b = torch.ones(1,2,2) + 2

img = torch.cat(
    (r,g,b)
    ,dim=0
)

img

tensor([[[1., 1.],
         [1., 1.]],

        [[2., 2.],
         [2., 2.]],

        [[3., 3.],
         [3., 3.]]])

In [72]:
img.shape

torch.Size([3, 2, 2])

In [73]:
img.flatten(start_dim=0)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [74]:
img.flatten(start_dim=1)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

## **Element-wise operations**

In [75]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)

t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype=torch.float32)

In [76]:
# Example of the first axis
print(t1[0])

tensor([1., 2.])


In [77]:
# Example of the second axis
print(t1[0][0])

tensor(1.)


In [78]:
t1[0][0]

tensor(1.)

In [79]:
t2[0][0]

tensor(9.)

### **Addition Is An Element-Wise Operation**

In [80]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

In [82]:
print(t1 + 2)
print(t1 - 2)
print(t1 * 2)
print(t1 / 2)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [83]:
print(t1.add(2))
print(t1.sub(2))
print(t1.mul(2))
print(t1.div(2))

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


## **Broadcasting TensorsNew Section**

In [84]:
np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])

In [85]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [86]:
t1 + torch.tensor(
    np.broadcast_to(2, t1.shape)
    ,dtype=torch.float32
)

tensor([[3., 4.],
        [5., 6.]])

## **Trickier Example Of Broadcasting**

In [89]:
t1 = torch.tensor([
    [1,1],
    [2,2]
], dtype=torch.float32)

t2 = torch.tensor([2,4], dtype=torch.float32)

In [91]:
np.broadcast_to(t2.numpy(), t1.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

In [90]:
t1 + t2

tensor([[3., 5.],
        [4., 6.]])

## **Comparison Operations Are Element-Wise**

In [92]:
torch.tensor([1, 2, 3]) < torch.tensor([3, 1, 2])

tensor([ True, False, False])

## **Element-Wise Comparison Operation Examples**

In [93]:
t = torch.tensor([
    [0,5,0],
    [6,0,7],
    [0,8,0]
], dtype=torch.float32)

In [94]:
t.eq(0)

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])

In [95]:
t.ge(0)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [96]:
t.gt(0)

tensor([[False,  True, False],
        [ True, False,  True],
        [False,  True, False]])

In [97]:
t.le(0)

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])

In [98]:
t.lt(0)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [99]:
t <= torch.tensor(
    np.broadcast_to(7, t.shape)
    ,dtype=torch.float32
)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

In [100]:
t <= torch.tensor([
    [7,7,7],
    [7,7,7],
    [7,7,7]
], dtype=torch.float32)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

## **Element-Wise Operations Using Functions**

In [101]:
t.abs() 

tensor([[0., 5., 0.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [102]:
t.sqrt() 

tensor([[0.0000, 2.2361, 0.0000],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [103]:
t.neg() 

tensor([[-0., -5., -0.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

In [104]:
t.neg().abs() 

tensor([[0., 5., 0.],
        [6., 0., 7.],
        [0., 8., 0.]])

There are some other ways to refer to element-wise operations, so I just wanted to mention that all of these mean the same thing:

1. Element-wise
2. Component-wise
3. Point-wise

## **Tensor Reduction Operations**

In [105]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)

In [106]:
t.sum()

tensor(8.)

In [107]:
t.numel()

9

In [108]:
t.sum().numel()

1

In [109]:
t.sum().numel() < t.numel()

True

## **Common Tensor Reduction Operations**

In [110]:
t.sum()

tensor(8.)

In [111]:
t.prod()

tensor(0.)

In [112]:
t.mean()

tensor(0.8889)

In [113]:
t.std()

tensor(1.1667)

## **Reducing Tensors By Axes**

In [114]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [115]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [116]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

## **Understanding Reductions By Axes**

In [117]:
t[0]

tensor([1., 1., 1., 1.])

In [120]:
t[1]

tensor([2., 2., 2., 2.])

In [121]:
t[2]

tensor([3., 3., 3., 3.])

In [122]:
t[0]+t[1]+t[2]

tensor([6., 6., 6., 6.])

## **Argmax Tensor Reduction Operation**

In [129]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
], dtype=torch.float32)

In [130]:
t.max()

tensor(5.)

In [133]:
t.argmax() # index value of max element in flatten tensor

tensor(11)

In [132]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [134]:
t.max(dim=0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [135]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [136]:
t.max(dim=1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 1, 3]))

In [137]:
t.argmax(dim=1)

tensor([3, 1, 3])

## **Accessing Elements Inside TensorsNew Section**

In [138]:
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float32)

In [139]:
t.mean()

tensor(5.)

In [140]:
t.mean().item()

5.0

In [141]:
t.mean(dim=0).tolist()

[4.0, 5.0, 6.0]

In [143]:
t.mean(dim=0).numpy()

array([4., 5., 6.], dtype=float32)